export enum Symbol {
  greaterThan = '>',
  lessThan = '<',
  equalTo = '=',
  openBrace = '{',
  closeBrace = '}',
  openSquareBracket = '[',
  closeSquareBracket = ']',
  colon = ':',
  doubleQuotation = '"',
  singleQuotation = "'",
  comma = ',',
  commet = '#',
  dot = '.',
  asterisk = '*',
  minus = '-',
}